apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactv_cd
  labels:
    app: reactv_cd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reactv_cd
  template:
    metadata:
      labels:
        app: reactv_cd
    spec:
      containers:
        - name: nextjs-container
          image: neathtan/nextjs-adv:9
          ports:
            - containerPort:  5173
